# Generated by Django 5.1.4 on 2024-12-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='arrival',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='depature',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
