# Generated by Django 5.1.4 on 2025-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_arrival_booking_depature_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='when',
            field=models.DateField(null=True),
        ),
    ]
